# Generated by Django 6.0.4 on 2026-04-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spanishapp", "0002_alter_studentprofile_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
