# Generated by Django 6.0.4 on 2026-04-25 19:39

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spanishapp", "0003_studentprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="nationality",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="country_of_birth",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="country_of_residence",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="country_of_birth",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="country_of_residence",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
