# Generated by Django 6.0.4 on 2026-05-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishapp', '0004_remove_studentprofile_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spanishapp.coursetype'),
        ),
    ]
