# Generated by Django 6.0.4 on 2026-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spanishapp", "0005_timeslot_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagelevel",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
