# Generated by Django 6.0.4 on 2026-05-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spanishapp", "0006_languagelevel_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="spanishapp.coursetype",
            ),
            preserve_default=False,
        ),
    ]
