# Generated by Django 6.0.4 on 2026-05-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spanishapp", "0007_alter_timeslot_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="spanishapp.languagelevel",
            ),
            preserve_default=False,
        ),
    ]
