# Generated by Django 6.0.4 on 2026-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spanishapp", "0008_alter_studentprofile_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
