# Generated by Django 6.0.4 on 2026-05-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishapp', '0009_booking_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('total_classes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spanishapp.classpackage'),
        ),
    ]
