# Generated by Django 6.0.4 on 2026-05-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spanishapp", "0010_classpackage_studentprofile_package"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("teacher", "start_date_time")},
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="course",
        ),
    ]
